apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrator.name" . }}-config
data:
  connections.yaml: |
    {{- toYaml .Values.connections | nindent 4 }}
  application.yaml: |
    {{- $base := dict "orchestrator" (dict "catalog-defaults" .Values.catalog) }}
    {{- toYaml (mergeOverwrite $base (deepCopy .Values.application)) | nindent 4 }}
